<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BackupController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth']);
    }

    /**
     * Download database backup as .sql file via mysqldump
     */
    public function download()
    {
        // Hanya Super Admin
        if (!auth()->user()->hasRole('SUPER_ADMIN')) {
            abort(403, 'Akses ditolak. Hanya Super Admin yang dapat melakukan backup database.');
        }

        $dbHost     = config('database.connections.mysql.host', '127.0.0.1');
        $dbPort     = config('database.connections.mysql.port', '3306');
        $dbName     = config('database.connections.mysql.database');
        $dbUser     = config('database.connections.mysql.username');
        $dbPassword = config('database.connections.mysql.password');

        $filename  = "backup_{$dbName}_" . date('Y-m-d_H-i-s') . ".sql";
        $backupDir = storage_path('app/backups');

        if (!is_dir($backupDir)) {
            mkdir($backupDir, 0755, true);
        }

        $outputFile = $backupDir . DIRECTORY_SEPARATOR . $filename;

        // Coba cari mysqldump di berbagai lokasi umum di Laragon/WAMP/XAMPP
        $possiblePaths = [
            'mysqldump',                                      // PATH global
            'C:\\laragon\\bin\\mysql\\mysql-8.0.30-winx64\\bin\\mysqldump.exe',
            'C:\\laragon\\bin\\mysql\\mysql-8.4.3-winx64\\bin\\mysqldump.exe',
            'C:\\xampp\\mysql\\bin\\mysqldump.exe',
            'C:\\wamp64\\bin\\mysql\\mysql8.0.31\\bin\\mysqldump.exe',
        ];

        // Cari yang tersedia
        $mysqldump = null;
        foreach ($possiblePaths as $path) {
            if ($path === 'mysqldump') {
                exec("mysqldump --version 2>&1", $out, $code);
                if ($code === 0) { $mysqldump = 'mysqldump'; break; }
            } elseif (file_exists($path)) {
                $mysqldump = '"' . $path . '"';
                break;
            }
        }

        // Coba scan folder Laragon bin dinamis
        if (!$mysqldump) {
            $laragonMysqlBin = glob('C:\\laragon\\bin\\mysql\\*\\bin\\mysqldump.exe');
            if (!empty($laragonMysqlBin)) {
                $mysqldump = '"' . $laragonMysqlBin[0] . '"';
            }
        }

        if (!$mysqldump) {
            return redirect()->back()->with('error',
                'mysqldump tidak ditemukan di sistem. Pastikan MySQL/Laragon terinstall dengan benar.'
            );
        }

        // Build command
        $passwordOption = $dbPassword ? "-p\"{$dbPassword}\"" : '';
        $command = "{$mysqldump} -h {$dbHost} -P {$dbPort} -u \"{$dbUser}\" {$passwordOption} \"{$dbName}\" > \"{$outputFile}\" 2>&1";

        exec($command, $output, $returnCode);

        if ($returnCode !== 0 || !file_exists($outputFile) || filesize($outputFile) < 100) {
            // Fallback: Buat SQL dari PHP jika mysqldump gagal
            $this->generateSqlFallback($outputFile, $dbName);
        }

        if (!file_exists($outputFile)) {
            return redirect()->back()->with('error', 'Gagal membuat file backup. Periksa permission folder storage/app/backups.');
        }

        // Log aktivitas backup
        activity()
            ->causedBy(auth()->user())
            ->withProperties(['file' => $filename, 'size' => filesize($outputFile)])
            ->log("Backup database <b>{$dbName}</b> berhasil diunduh oleh <b>" . auth()->user()->name . "</b>.");

        return response()->download($outputFile, $filename, [
            'Content-Type'        => 'application/sql',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ])->deleteFileAfterSend(true);
    }

    /**
     * Fallback: Generate SQL menggunakan PHP PDO jika mysqldump tidak tersedia
     */
    private function generateSqlFallback(string $outputFile, string $dbName): void
    {
        $handle = fopen($outputFile, 'w');

        fputs($handle, "-- ============================================================\n");
        fputs($handle, "-- Backup Database: {$dbName}\n");
        fputs($handle, "-- Generated at  : " . now()->toDateTimeString() . "\n");
        fputs($handle, "-- Generated by  : Almahira HR System (PHP Fallback)\n");
        fputs($handle, "-- ============================================================\n\n");
        fputs($handle, "SET FOREIGN_KEY_CHECKS=0;\n\n");

        $tables = DB::select('SHOW TABLES');
        $tableKey = "Tables_in_{$dbName}";

        foreach ($tables as $tableObj) {
            $table = $tableObj->$tableKey ?? array_values((array)$tableObj)[0];

            // CREATE TABLE statement
            $createResult = DB::select("SHOW CREATE TABLE `{$table}`");
            if (!empty($createResult)) {
                $createSql = array_values((array)$createResult[0])[1];
                fputs($handle, "\n-- Table: {$table}\n");
                fputs($handle, "DROP TABLE IF EXISTS `{$table}`;\n");
                fputs($handle, $createSql . ";\n\n");
            }

            // INSERT DATA
            $rows = DB::table($table)->get();
            if ($rows->isEmpty()) continue;

            $columns = implode('`, `', array_keys((array)$rows->first()));
            fputs($handle, "INSERT INTO `{$table}` (`{$columns}`) VALUES\n");

            $chunks = $rows->chunk(100);
            $lastChunkIndex = $chunks->count() - 1;

            foreach ($chunks as $chunkIndex => $chunk) {
                $values = $chunk->map(function ($row) {
                    $escaped = array_map(function ($val) {
                        if (is_null($val)) return 'NULL';
                        return "'" . addslashes((string)$val) . "'";
                    }, (array)$row);
                    return '(' . implode(', ', $escaped) . ')';
                })->implode(",\n");

                $separator = ($chunkIndex === $lastChunkIndex) ? ";\n\n" : ",\n";
                fputs($handle, $values . $separator);
            }
        }

        fputs($handle, "SET FOREIGN_KEY_CHECKS=1;\n");
        fclose($handle);
    }
}
